# Generated by Django 4.2.3 on 2023-07-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religion', '0002_delete_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': '历程',
                'verbose_name_plural': '历程',
            },
        ),
    ]
